version: '3.8'

services:
  manager:
    build:
      context: ./manager
    ports:
      - "8080:8080"
    environment:
      - WORKER_URLS=http://worker1:8081,http://worker2:8081,http://worker3:8081
    networks:
      - crackhash-net

  worker1:
    build:
      context: ./worker
    environment:
      - MANAGER_URL=http://manager:8080
    networks:
      - crackhash-net
    depends_on:
      - manager

  worker2:
    build:
      context: ./worker
    environment:
      - MANAGER_URL=http://manager:8080
    networks:
      - crackhash-net
    depends_on:
      - manager

  worker3:
    build:
      context: ./worker
    environment:
      - MANAGER_URL=http://manager:8080
    networks:
      - crackhash-net
    depends_on:
      - manager

networks:
  crackhash-net:
    driver: bridge